version: '3.9'

services:
  database:
    image: postgres
    container_name: database_games_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=games
      - POSTGRES_PASSWORD=games
      - POSTGRES_DB=games_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: games_api_app
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local